openapi: 3.0.1
info:
  title: Httpbin
  description: ''
  version: '1.0'
servers:
  - url: https://apimlab3-leaf.com/httpbin
paths:
  /get:
    get:
      summary: Get
      operationId: get
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]