openapi: 3.0.1
info:
  title: TestAPI1
  description: ''
  version: '1.0'
servers:
  - url: https://apimlab3-leaf.com/test1
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]